version: '3'
services:
# Jupyterlab Datascience Container
  jupyter-lab:
    container_name: ${JUPYTERLAB_CONTAINER_NAME}
    image: ${JLAB_IMAGE}:${JLAB_TAG}
    restart: always
    volumes:
    - jovyan_home:/home/jovyan
    - ${NOTEBOOKS_DATA:?err}:/home/jovyan/work
    networks:
    - default
    ports:
    - "${JLAB_HOST_PORT}:8888"
    environment:
    - IEX_TOKEN=${IEX_TOKEN}
    - ALPHA_VANTAGE_API=${ALPHA_VANTAGE_API}
    - PG_HOSTNAME=${POSTGRES_CONTAINER_NAME}
    - PG_PASSWORD=${PG_PASSWORD:?err}
    - PGPASSFILE=/home/jovyan/.pgpass
    command: ["jupyter", "lab"]

# PostgreSQL Database
  db-postgres:
   container_name: ${POSTGRES_CONTAINER_NAME}
   image: postgres:${PG_TAG}
   restart: always
   volumes:
   - pg_db:/var/lib/postgresql/data
   networks:
   - default
   ports:
   - "${PG_HOST_PORT}:5432"
   environment:
   - POSTGRES_PASSWORD=${PG_PASSWORD:?err}

# Volumes
volumes:
  jovyan_home:
  pg_db:

# Networks
networks:
# Defines default local network created externally
  default:
    external:
      name: local_network
